# Generated by Django 4.0.4 on 2022-05-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownrent',
            name='imagesale1',
        ),
        migrations.RemoveField(
            model_name='ownrent',
            name='imagesale2',
        ),
        migrations.AddField(
            model_name='ownrent',
            name='imagerent1',
            field=models.ImageField(blank=True, null=True, upload_to='images_rent/'),
        ),
        migrations.AddField(
            model_name='ownrent',
            name='imagerent2',
            field=models.ImageField(blank=True, null=True, upload_to='images_rent/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='number2',
            field=models.TextField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
