from django.db import models


class Register(models.Model):
    fname = models.TextField(max_length=50)
    lname = models.TextField(max_length=50)
    uname = models.TextField(max_length=50,   unique=True)
    email = models.EmailField(max_length=254,blank=True,null=True)
    number1 = models.TextField(max_length=50, unique=True)
    number2 = models.TextField(max_length=50,blank=True,null=True)
    pin = models.TextField(max_length=50)
    cpin = models.TextField(max_length=50)

class Ownsale(models.Model):
    sale_id = models.AutoField(primary_key=True)
    sale = models.TextField(max_length=10)
    prop_type = models.TextField(max_length=50)
    area = models.TextField(max_length=20)
    car_built = models.TextField(max_length=20)
    floor = models.TextField(max_length=20)
    total_floor = models.TextField(max_length=20)
    prop_age = models.TextField(max_length=30)
    prop_status = models.TextField(max_length=30)
    landmark = models.TextField(max_length=50)
    location = models.TextField(max_length=50)
    selling_price = models.TextField(max_length=50)
    avail = models.DateField()
    furnish = models.TextField(max_length=50)
    lift = models.TextField(max_length=30,blank=True,null=True)
    gym = models.TextField(max_length=30,blank=True,null=True)
    swimming_pool = models.TextField(max_length=30,blank=True,null=True)
    pets_allowed = models.TextField(max_length=30,blank=True,null=True)
    wifi_internet = models.TextField(max_length=30,blank=True,null=True)
    camera = models.TextField(max_length=30,blank=True,null=True)
    club_house = models.TextField(max_length=30,blank=True,null=True)
    fire_safety = models.TextField(max_length=30,blank=True,null=True)
    two_wheeler = models.TextField(max_length=30,blank=True,null=True)
    four_wheeler = models.TextField(max_length=30,blank=True,null=True)
    gas_pipe = models.TextField(max_length=30,blank=True,null=True)
    phone_intercom = models.TextField(max_length=30,blank=True,null=True)
    power_backup = models.TextField(max_length=30,blank=True,null=True)
    servant_room = models.TextField(max_length=30,blank=True,null=True)
    security_guard = models.TextField(max_length=30,blank=True,null=True)
    house_keeping = models.TextField(max_length=30,blank=True,null=True)
    air_conditioning = models.TextField(max_length=30,blank=True,null=True)
    children_ground = models.TextField(max_length=30,blank=True,null=True)
    sale_img = models.ImageField(upload_to='images/',blank=True,null=True)
    imagesale1 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagesale2 = models.ImageField(upload_to='images/', blank=True, null=True)
    comment = models.TextField(max_length=5000)

class Ownrent(models.Model):
    rent_id = models.AutoField(primary_key=True)
    rent = models.TextField(max_length=10)
    prop_type = models.TextField(max_length=50)
    area = models.TextField(max_length=20)
    car_built = models.TextField(max_length=20)
    floor = models.TextField(max_length=20)
    total_floor = models.TextField(max_length=20)
    prop_age = models.TextField(max_length=30)
    prop_status = models.TextField(max_length=30)
    landmark = models.TextField(max_length=50)
    location = models.TextField(max_length=50)
    ask_rent = models.TextField(max_length=50)
    deposit = models.TextField(max_length=50)
    avail = models.DateField()
    furnish = models.TextField(max_length=50)
    lift = models.TextField(max_length=30,blank=True,null=True)
    gym = models.TextField(max_length=30,blank=True,null=True)
    swimming_pool = models.TextField(max_length=30,blank=True,null=True)
    pets_allowed = models.TextField(max_length=30,blank=True,null=True)
    wifi_internet = models.TextField(max_length=30,blank=True,null=True)
    camera = models.TextField(max_length=30,blank=True,null=True)
    club_house = models.TextField(max_length=30,blank=True,null=True)
    fire_safety = models.TextField(max_length=30,blank=True,null=True)
    two_wheeler = models.TextField(max_length=30,blank=True,null=True)
    four_wheeler = models.TextField(max_length=30,blank=True,null=True)
    gas_pipe = models.TextField(max_length=30,blank=True,null=True)
    phone_intercom = models.TextField(max_length=30,blank=True,null=True)
    power_backup = models.TextField(max_length=30,blank=True,null=True)
    servant_room = models.TextField(max_length=30,blank=True,null=True)
    security_guard = models.TextField(max_length=30,blank=True,null=True)
    house_keeping = models.TextField(max_length=30,blank=True,null=True)
    air_conditioning = models.TextField(max_length=30,blank=True,null=True)
    children_ground = models.TextField(max_length=30,blank=True,null=True)
    rent_img = models.ImageField(upload_to='images_rent/',blank=True,null=True)
    imagerent1 = models.ImageField(upload_to='images_rent/', blank=True, null=True)
    imagerent2 = models.ImageField(upload_to='images_rent/', blank=True, null=True)
    comment = models.TextField(max_length=5000)

class Office_Staff(models.Model):
    employee_id = models.AutoField(primary_key=True)
    first_name = models.TextField(max_length=50)
    last_name = models.TextField(max_length=50)
    username = models.TextField(max_length=50,unique=True)
    password = models.TextField(max_length=50)
    confirm_password = models.TextField(max_length=50)